# Site settings
title: The Second UK AI Conference 2024
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the web page of the Second UK AI Conference 2024.
baseurl: "/ukai2024" # the subpath of your site, e.g. /blog/
url: "http://uk-ai.org" # the base hostname & protocol for your site
github_username:  uk-ai


youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: ukai2024
  
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme

remote_theme: uk-ai/jekyll-theme

# Build settings
future: true


analytics:
 google:
   tracking_id: # Google tracking ID if applicable

youtube:
  height: 315
  width: 560


collections:
  sessions:
    output: true
    permalink: "/:categories/:title.html"

